apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{.Release.Name}}"
  namespace: "{{}}"
type: Opaque
stringData:
    PASSWORD_ELK: {{.Values.secrets.elk_pass}}
    arnSecret={{.Values.secret.arnSecret}}
    cluster={{.Values.secret.cluster}}
    container={{.Values.secret.container}}
    cpu={{.Values.secret.cpu}}
    dockerImage={{.Values.secret.dockerImage}}
    executionRole={{.Values.secret.executionRole}}
    logsGroup={{.Values.secret.logsGroup}}
    memory={{.Values.secret.memory}}
    region={{.Values.secret.region}}
    securityGroup={{.Values.secret.securityGroup}}
    service={{.Values.secret.service}}
    service-connection={{.Values.secret.serviceConnection}}
    subnet1={{.Values.secret.subnet1}}
    subnet2={{.Values.secret.subnet2}}
    task={{.Values.secret.task}}
    taskRole={{.Values.secret.taskRole}}
